### ISSUE TITLE
Error when quantity reaches 0

### ISSUE THREAD

**Issue by cdm-analytics** [vst/accfifo#3]
Hello!

I have been working with your code and it is fantastic! Thank you!

I ran into an issue where I was getting an "AssertionError" if the cumulative quantity of trades reached 0.

To reproduce:
`el = [Trade(pd.to_datetime('01.03.2016',format='%d.%m.%Y'), 68, 15)]`
`el.append(Trade(pd.to_datetime('05.03.2016',format='%d.%m.%Y'), -68, 15.5))`
`b = Isin('bond', 1, el)`
`trans = FifoAccount(b)`

I then changed the last line of the FifoAccount class to:
`assert(self._quantity >= 0)`

That seems to have resolved the error and I believe that the output is still correct.

I'm wondering if this was a bug or if, perhaps, there is something I am misunderstanding about FIFO accounting.

**Comment by vst** [comment]
Hello,

Glad to hear that the library is somewhat useful.

Can you check this:

https://github.com/vst/accfifo/blob/main/test_accfifo.py#L130

This mimics your example. But, I do not know what `FifoAccount` is.

BTW: I am no longer using this library. Sorry in advance.
